### ISSUE TITLE
Add nickname autofilling to the sign up form

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim#1]
**Is your feature request related to a problem? Please describe.**
Our clients report that many of their users do not understand the difference between name and nickname when they sign up :

    some don’t know what to input (it can be creative out of the blue ;))
    some feel like they are asked to input the same info twice and find it annoying
    some will create errors by inputing special characters* or going over the limit (25)
    Constraint not mentioned in a help text that the user discovers with an error message after sending the form

This creates unnecessary frictions at a crucial step.

**Describe the solution you'd like**
In order to make it easier to sign up on Decidim, we propose

    to automatically fill the user nickname field using the name input
    hide the nickname field on the signup form to avoid any confusion*

*(what is this second field ? why is it autofilled ?) + they can always change it later in their account settings

We propose to generate the nickname in the following way :

    delete spaces
    no uppercase
    delete special characters
    25 characters
    when duplacate add a number that can be incremented
    keep 2 characters for numbers at the end

Example :

Name : Constantin Guillaume de La villardière → Nickname : constantinguillaumedela

If a other users register with the same name we’ll have :

constantinguillaumedela1

constantinguillaumedela2

.

.

constantinguillaumedela99

**Describe alternatives you've considered**
Open :)

**Additional context**
This was tried by Platoniq on one of their instance, they told us it really helped with registration.

This proposal is part of a larger scope to improve authentication flow in Decidim. Working document here (External link) 
(Enllaç extern).

Does this issue could impact on users private data?
No

**Funded by**
OSP and Angers

**Comment by paarals** [comment]
You can try it: https://decidim-signup.dev.pokecode.net/users/sign_up?locale=fr

**Comment by simonaszilinskas** [comment]
Great job! 

We just found a few little bugs: 
- the nickname field is not masked
- the character limit for the nickname is not respected (screenshot attached)

![image](https://user-images.githubusercontent.com/14858948/175059927-5b76eafb-2ee2-468d-be1f-683c75c5ce36.png)

**Comment by microstudi** [comment]
thanks @simonaszilinskas !
one question, what do you mean is not masked?

**Comment by simonaszilinskas** [comment]
Reference from the [Metadecidim proposal](https://meta.decidim.org/processes/roadmap/f/122/proposals/17029?commentId=25317):

"
In order to make it easier to sign up on Decidim, we propose:
- to automatically fill the user nickname field using the name input
**- hide the nickname field on the signup form to avoid any confusion***
*(what is this second field ? why is it autofilled ?) + they can always change it later in their account settings
"

So there should be no option to change the nickname field in the sign up form - only later on in the settings

**Comment by microstudi** [comment]
I personally don't like this option, all the work done here has little sense if we do that.
I personally advocate for explaining better what is the nickname and what is it used for. For instance "having a nickname gives you the ability to participate more effectively and mention other users while making comments".
Can we confirm this is what we all really want? 
CC @carolromero @andreslucena

**Comment by simonaszilinskas** [comment]
Thanks for the reply!

The option to choose a nickname for those that want it does not disappear, nor do the functionalities attached to it. In the same way that most user facing services use nicknames to identify users, Decidim would continue to do it as well. The autofilling of the nickname would just take away the burden of understanding it away from the crucial sign up process. 

Glad to discuss it further!

**Comment by virgile-dev** [comment]
Hello @microstudi Decidim product is in favor of masking the nickname field on the sign up form : 
Check this comment from carol : 
https://meta.decidim.org/processes/roadmap/f/122/proposals/17029?commentId=25301#comment_25301

**Comment by carolromero** [comment]
@microstudi we discussed this with the product and redesign team, and we believe that this will reduce the cognitive load at the time of registration. In addition, the idea is to progressively reduce the prominence of the nickname throughout the interface. The thing is that the nickname it is used mainly for mentions, but what if you could mention people directly by name? So, to give you a bigger picture, this is a first step to gradually abandon the use of the nickname.

**Comment by virgile-dev** [comment]
I posted this comment on meta decidim : https://meta.decidim.org/processes/roadmap/f/122/proposals/17029?commentId=25326#comment_25326
But since you are thinking of getting rid of the nickname or merge name and nickname I'm guessing we have to hide it then.
