### ISSUE TITLE
Add show password option on sign in, sign up and forgot password forms

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim#2]
**Is your feature request related to a problem? Please describe.**
**Problem**

We’ve had a lot of support tickets from users who had a really hard time typing a 10 character long password twice without making any error.

As there isn’t instant input validation on the password field many ran into the error “passwords do not match” several times when sending the form.

For existing users who tried to sign in, not being able to see what they were typing leads to think they forgot their password.

During user testing we’ve seen users type their password in the email field first (sometimes on an external text editor) and then copy paste it in the password field to make sure they weren’t making any mistakes. On mobile this can be particularly painful for the user.

**Describe the solution you'd like**
As a user who needs to type a password on a Decidim form I should have a show password option so I can proofread what I’m typing.

On most website this option is offered directly on the field using an eye icon. For accessibility reasons we think it might be better to add a checkbox bellow the password fields (like twitter is doing).

Mockup: 
Proposal OSP: https://www.figma.com/proto/xpUjY6urnlyn1yVW300208/Improve-Sign-up%2Fin?page-id=0%3A1&node-id=2%3A624&viewport=2020%2C542%2C0.26&scaling=min-zoom
Proposal CORE (follow the eye): https://www.figma.com/proto/3CNSXeFTMtUl2QdEUgLpEo/Decidim-PX?page-id=7276%3A117981&node-id=7276%3A145728&viewport=530%2C463%2C0.02&scaling=min-zoom&starting-point-node-id=7276%3A216610 

so we have to follow the eye icon to do that

**Describe alternatives you've considered**
Get rid of password using magic links (External link) 
(Enllaç extern)

**Additional context**
This proposal is part of a larger scope to improve authentication flow in Decidim. Working document here (External link) 
(Enllaç extern).

**Does this issue could impact on users private data?**
No

**Funded by**
Angers and OSP

**Comment by simonaszilinskas** [comment]
Great work - verified the accessibility and everything seems to work fine! The only concern I have is the block icon (in the show state). I suppose there is no crossed eye icon in the Decidim library so you decided to use this, but I think a crossed eye would be way better - could we just reuse the current icon and add a bar on it? Maybe that wouldn't be too contrary to the current design language. What do you think?

**Comment by microstudi** [comment]
Not sure how to do that, we can always add an extra icon, but to be honest, not sure if they going to like it.
Do you know of some css only solution for this? (I'll look it myself too).
We could also upgrade the general svg adding this icon, but that's out of scope

**Comment by simonaszilinskas** [comment]
The easiest way to do it I see is to put an SVG rectangle on top of the eye icon. Either covering it fully or just covering the white space in the middle. 

What do you think?

**Comment by microstudi** [comment]
I've managed to do it with pure CSS, looks like this:
![Screenshot from 2022-06-30 12-43-35](https://user-images.githubusercontent.com/1401520/176658487-f9327b36-3a52-482e-9603-99c5a6bc9c7c.png)

**Comment by simonaszilinskas** [comment]
Thank you for this very nice try! The icon looks a little uneven, but that's not that important - glad to know it is possible to do! I think let's keep it as it was and if the Barcelona team prefers the barred eye - we'll go with it.
