### ISSUE TITLE
Improve notifications to valuators

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim#49]
in #23 we send an email to valuators, we need some changes:

- [x] Remove "assigned by XXX".
- [x] Add a link to the backend (similar as when a proposal is created) to admin the proposal assigned

**Comment by paarals** [comment]
shall we close that? @microstudi @antopalidi

**Comment by antopalidi** [comment]
> shall we close that? @microstudi @antopalidi

Yes, it' s done
